FROM php:7.2-fpm

# Update and install common packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    g++ \
    unzip \
    curl \
    iputils-ping \
    wget \
    htop \
    apt-utils \
    gnupg \
    software-properties-common \
    apt-transport-https \
    libxml2-dev \
    vim

# Update and install common packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    libaio-dev \
    freetds-dev \
    libssl-dev \
    openssl \
    supervisor

# Redis - php config 
RUN pecl install redis-5.1.0 \
    && docker-php-ext-enable redis    

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.0.2 \
    && composer --version  

# Install PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql

RUN apt-get install -y zlib1g-dev libicu-dev g++ libzip-dev git && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl zip sockets && \
    apt-get purge -y g++          

ENV TZ=Europe/Madrid    
